ALTER TABLE products ADD COLUMN IF NOT EXISTS weight_grams INTEGER NOT NULL DEFAULT 500;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dim_length_cm INTEGER NOT NULL DEFAULT 20;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dim_width_cm INTEGER NOT NULL DEFAULT 20;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dim_height_cm INTEGER NOT NULL DEFAULT 20;
