-- 047: editable SEO fields for products, categories, subcategories

ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_h1 TEXT NOT NULL DEFAULT '';

ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_title TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_description TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_h1 TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_intro_top TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_text_bottom TEXT NOT NULL DEFAULT '';

ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS seo_title TEXT NOT NULL DEFAULT '';
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS seo_description TEXT NOT NULL DEFAULT '';
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS seo_h1 TEXT NOT NULL DEFAULT '';
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS seo_intro_top TEXT NOT NULL DEFAULT '';
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS seo_text_bottom TEXT NOT NULL DEFAULT '';
